"""Many to many #2?

Revision ID: 15e996e7ae2d
Revises: 994554a011aa
Create Date: 2022-12-20 08:42:32.224297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e996e7ae2d'
down_revision = '994554a011aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cat_customer_id_fkey', 'cat', type_='foreignkey')
    op.drop_column('cat', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cat_customer_id_fkey', 'cat', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###
